# Auto-generated from lora_proto.h by gen_lora_proto_py.py
# Generated: 2026-01-14 14:00:54
# DO NOT EDIT THIS FILE BY HAND.


PROTO_VER_MAJOR = 1
PROTO_VER_MINOR = 4
BODY_MAX = 20
DIR_M2N = 0
DIR_N2M = 128
ACK_BAD_LEN = 2
ACK_BAD_TYPE = 1
ACK_BUSY = 4
ACK_ERROR = 5
ACK_OK = 0
ACK_UNAUTHORIZED = 3
OPC_ACK = 126
OPC_CONFIG = 5
OPC_CONTROL = 4
OPC_DEVICES = 1
OPC_SET_GROUP = 2
OPC_STATUS = 3
OPC_STREAM = 7
OPC_SYNC = 6
RESP_ACK = 1
RESP_NONE = 0
RESP_SPECIFIC = 2

def type_dir(t: int) -> int: return t & 0x80
def type_base(t: int) -> int: return t & 0x7F
def flip_dir(t: int) -> int: return t ^ 0x80
def make_type(dir_: int, opcode7: int) -> int: return (dir_ | (opcode7 & 0x7F))

# Packed struct sizes (bytes)
SZ_Header7 = 7
SZ_P_Ack = 3
SZ_P_Config = 5
SZ_P_Control = 4
SZ_P_GetDevices = 2
SZ_P_GetStatus = 2
SZ_P_IdentifyReply = 9
SZ_P_SetGroup = 1
SZ_P_StatusReply = 8
SZ_P_Stream = 9
SZ_P_Sync = 4

from dataclasses import dataclass
from typing import Dict, List, Optional

@dataclass(frozen=True)
class PacketRule:
    opcode7: int
    req_dir: int
    policy: int
    rsp_opcode7: int
    req_len: int
    rsp_len: int
    name: str

RULES: List[PacketRule] = [
    PacketRule(1, 0, 2, 1, 2, 9, 'DEVICES/IDENTIFY'),
    PacketRule(2, 0, 1, 126, 1, 3, 'SET_GROUP'),
    PacketRule(3, 0, 2, 3, 2, 8, 'STATUS'),
    PacketRule(4, 0, 0, 0, 4, 0, 'CONTROL'),
    PacketRule(5, 0, 1, 126, 5, 3, 'CONFIG'),
    PacketRule(6, 0, 0, 0, 4, 0, 'SYNC'),
    PacketRule(7, 0, 1, 126, 9, 3, 'STREAM_M2N'),
]

RULES_BY_OPCODE7: Dict[int, PacketRule] = {r.opcode7: r for r in RULES}

def find_rule(opcode7: int) -> Optional[PacketRule]:
    return RULES_BY_OPCODE7.get(int(opcode7) & 0x7F)

