# Auto-generated from racelink_proto.h by gen_racelink_proto_py.py
# Generated: 2026-04-24 15:37:26
# DO NOT EDIT THIS FILE BY HAND.


PROTO_VER_MAJOR = 2
PROTO_VER_MINOR = 0
BODY_MAX = 22
DIR_M2N = 0
DIR_N2M = 128
ACK_BAD_LEN = 2
ACK_BAD_TYPE = 1
ACK_BUSY = 4
ACK_ERROR = 5
ACK_OK = 0
ACK_UNAUTHORIZED = 3
OPC_ACK = 126
OPC_CONFIG = 5
OPC_CONTROL = 4
OPC_CONTROL_ADV = 8
OPC_DEVICES = 1
OPC_SET_GROUP = 2
OPC_STATUS = 3
OPC_STREAM = 7
OPC_SYNC = 6
RESP_ACK = 1
RESP_NONE = 0
RESP_SPECIFIC = 2

def type_dir(t: int) -> int: return t & 0x80
def type_base(t: int) -> int: return t & 0x7F
def flip_dir(t: int) -> int: return t ^ 0x80
def make_type(dir_: int, opcode7: int) -> int: return (dir_ | (opcode7 & 0x7F))

# Packed struct sizes (bytes)
SZ_Header7 = 7
SZ_P_Ack = 3
SZ_P_Config = 5
SZ_P_Control = 4
SZ_P_GetDevices = 2
SZ_P_GetStatus = 2
SZ_P_IdentifyReply = 9
SZ_P_SetGroup = 1
SZ_P_StatusReply = 8
SZ_P_Stream = 9
SZ_P_Sync = 4

# Packed struct field layouts extracted from racelink_proto.h
STRUCT_FIELDS = {
    'Header7': [
        ('sender', 'uint8_t', 3),
        ('receiver', 'uint8_t', 3),
        ('type', 'uint8_t', 1),
    ],
    'P_Ack': [
        ('echo_opcode7', 'uint8_t', 1),
        ('status', 'uint8_t', 1),
        ('seq', 'uint8_t', 1),
    ],
    'P_Config': [
        ('option', 'uint8_t', 1),
        ('data0', 'uint8_t', 1),
        ('data1', 'uint8_t', 1),
        ('data2', 'uint8_t', 1),
        ('data3', 'uint8_t', 1),
    ],
    'P_Control': [
        ('groupId', 'uint8_t', 1),
        ('flags', 'uint8_t', 1),
        ('presetId', 'uint8_t', 1),
        ('brightness', 'uint8_t', 1),
    ],
    'P_GetDevices': [
        ('groupId', 'uint8_t', 1),
        ('flags', 'uint8_t', 1),
    ],
    'P_GetStatus': [
        ('groupId', 'uint8_t', 1),
        ('flags', 'uint8_t', 1),
    ],
    'P_IdentifyReply': [
        ('fw', 'uint8_t', 1),
        ('caps', 'uint8_t', 1),
        ('groupId', 'uint8_t', 1),
        ('mac6', 'uint8_t', 6),
    ],
    'P_SetGroup': [
        ('groupId', 'uint8_t', 1),
    ],
    'P_StatusReply': [
        ('flags', 'uint8_t', 1),
        ('configByte', 'uint8_t', 1),
        ('presetId', 'uint8_t', 1),
        ('brightness', 'uint8_t', 1),
        ('vbat_mV', 'uint16_t', 1),
        ('rssi', 'int8_t', 1),
        ('snr', 'int8_t', 1),
    ],
    'P_Stream': [
        ('ctrl', 'uint8_t', 1),
        ('data', 'uint8_t', 8),
    ],
    'P_Sync': [
        ('ts24_0', 'uint8_t', 1),
        ('ts24_1', 'uint8_t', 1),
        ('ts24_2', 'uint8_t', 1),
        ('brightness', 'uint8_t', 1),
    ],
}

from dataclasses import dataclass
from typing import Dict, List, Optional

@dataclass(frozen=True)
class PacketRule:
    opcode7: int
    req_dir: int
    policy: int
    rsp_opcode7: int
    req_len: int
    rsp_len: int
    name: str

RULES: List[PacketRule] = [
    PacketRule(1, 0, 2, 1, 2, 9, 'DEVICES/IDENTIFY'),
    PacketRule(2, 0, 1, 126, 1, 3, 'SET_GROUP'),
    PacketRule(3, 0, 2, 3, 2, 8, 'STATUS'),
    PacketRule(4, 0, 0, 0, 4, 0, 'CONTROL'),
    PacketRule(8, 0, 0, 0, 0, 0, 'CONTROL_ADV'),
    PacketRule(5, 0, 1, 126, 5, 3, 'CONFIG'),
    PacketRule(6, 0, 0, 0, 4, 0, 'SYNC'),
    PacketRule(7, 0, 1, 126, 9, 3, 'STREAM_M2N'),
]

RULES_BY_OPCODE7: Dict[int, PacketRule] = {r.opcode7: r for r in RULES}

def find_rule(opcode7: int) -> Optional[PacketRule]:
    return RULES_BY_OPCODE7.get(int(opcode7) & 0x7F)

