"""First-time-setup helper for the firmware-update flow.

Linux-only. Grants the running RaceLink user unattended access to the
``nmcli`` actions the OTA path uses (``dev wifi connect``, ``con down``,
radio toggle). Without this rule, NetworkManager's default polkit
policy denies those actions for non-root users — the operator sees
``Error: Insufficient privileges`` and the OTA aborts before the host
can associate to the WLED node's AP.

Bundled as a console script so a fresh ``pip install racelink-host``
exposes a single command:

    sudo racelink-setup-nmcli            # apply for $SUDO_USER
    sudo racelink-setup-nmcli alice      # apply for a specific user

The work it does is the same as the legacy ``scripts/setup_nmcli_polkit.sh``
(kept around for git-clone workflows): adds the user to ``netdev``
(Debian/Ubuntu/Pi OS) or ``wheel`` (Fedora/RHEL) if either group exists,
writes the polkit rule at ``/etc/polkit-1/rules.d/49-racelink-nmcli.rules``,
reloads polkit. Idempotent — re-running is safe.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from typing import List, Optional

# ``pwd`` and ``grp`` are stdlib modules on Linux only — the platform
# we actually run this script on. Lazy-imported inside the helpers that
# need them so importing the module on Windows (for the tests, or for
# anyone packaging this from a non-Linux CI box) doesn't blow up.

POLKIT_RULE_PATH = "/etc/polkit-1/rules.d/49-racelink-nmcli.rules"


def _polkit_rule_text(user: str) -> str:
    """Return the polkit JS rule that grants ``user`` unattended access
    to NetworkManager actions. Kept identical to the bash script's
    output so the two helpers produce a byte-equivalent rule file."""
    return (
        "// Auto-generated by racelink-setup-nmcli.\n"
        f"// Grants {user} unattended access to NetworkManager actions\n"
        "// (wifi connect, radio toggle, profile up/down) used by the\n"
        "// OTA flow. Re-run racelink-setup-nmcli if you rename the user.\n"
        "polkit.addRule(function(action, subject) {\n"
        '    if (action.id.indexOf("org.freedesktop.NetworkManager.") === 0 &&\n'
        f'        subject.user === "{user}") {{\n'
        "        return polkit.Result.YES;\n"
        "    }\n"
        "});\n"
    )


def _resolve_target_user(argv: List[str]) -> str:
    """Pick the user the polkit rule should authorise.

    CLI arg wins (so an admin can run ``sudo racelink-setup-nmcli alice``
    on behalf of someone else); ``$SUDO_USER`` covers the typical
    ``sudo racelink-setup-nmcli`` invocation. Raises ``RuntimeError`` if
    neither yields a real user — printing the friendly ``usage`` line
    is the caller's job.
    """
    if len(argv) >= 2 and argv[1].strip():
        return argv[1].strip()
    sudo_user = os.environ.get("SUDO_USER", "").strip()
    if sudo_user:
        return sudo_user
    raise RuntimeError("no username supplied and $SUDO_USER is empty")


def _user_exists(name: str) -> bool:
    import pwd  # lazy: Linux-only stdlib module
    try:
        pwd.getpwnam(name)
    except KeyError:
        return False
    return True


def _add_to_group(user: str, group: str) -> bool:
    """Add ``user`` to ``group`` if the group exists. Returns ``True``
    when the group exists (regardless of whether membership had to be
    added) so the caller knows whether to try a fallback group. Errors
    from ``usermod`` propagate so the operator sees them instead of a
    silent half-finished setup."""
    try:
        import grp
        grp.getgrnam(group)
    except KeyError:
        return False
    # Already a member? Skip the usermod call so re-runs don't churn
    # /etc/group's mtime and stay strictly idempotent.
    try:
        members = set(grp.getgrnam(group).gr_mem)
    except KeyError:
        members = set()
    if user in members:
        print(f"user {user!r} already in group {group!r}.")
        return True
    proc = subprocess.run(
        ["usermod", "-aG", group, user],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"usermod -aG {group} {user} failed ({proc.returncode}): "
            f"{(proc.stderr or proc.stdout).strip()}"
        )
    print(
        f"added {user!r} to group {group!r}. Log out and back in for "
        "this to take effect."
    )
    return True


def _install_groups(user: str) -> None:
    """Add the user to ``netdev`` (Debian-family) or fall back to
    ``wheel`` (Fedora/RHEL). Skipping silently is OK — the polkit rule
    below is the load-bearing piece; group membership is just defence
    in depth for distros whose nmcli policy keys off it."""
    if _add_to_group(user, "netdev"):
        return
    if _add_to_group(user, "wheel"):
        return
    print(
        "note: neither netdev nor wheel group present; relying on "
        "polkit rule below."
    )


def _write_polkit_rule(user: str) -> None:
    """Write the polkit rule atomically.

    Atomic via ``os.replace`` so a partial write can't leave the system
    with a syntactically broken rule that would lock the operator out
    of *all* nmcli actions until they fix it.
    """
    rule = _polkit_rule_text(user)
    parent = os.path.dirname(POLKIT_RULE_PATH)
    os.makedirs(parent, exist_ok=True)
    tmp = POLKIT_RULE_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(rule)
    os.chmod(tmp, 0o644)
    os.replace(tmp, POLKIT_RULE_PATH)
    print(f"wrote {POLKIT_RULE_PATH}")


def _reload_polkit() -> None:
    """Pick up the new rule without a reboot. ``systemctl reload`` is
    the documented entry; some older distros only support ``restart``;
    if neither path works we print a hint and let the operator reboot."""
    if not shutil.which("systemctl"):
        print(
            "note: systemctl not available; reboot to activate the "
            "polkit rule."
        )
        return
    for verb in ("reload", "restart"):
        proc = subprocess.run(
            ["systemctl", verb, "polkit"],
            capture_output=True, text=True,
        )
        if proc.returncode == 0:
            return
    print(
        "warning: could not reload polkit via systemctl; reboot to "
        "activate the new rule."
    )


def _check_nmcli() -> Optional[str]:
    """Return the install hint for the running distro when ``nmcli`` is
    missing, or ``None`` if it's present.
    """
    if shutil.which("nmcli"):
        return None
    distro = ""
    try:
        with open("/etc/os-release", "r", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("ID=") or line.startswith("ID_LIKE="):
                    distro += " " + line.split("=", 1)[1].strip().strip('"')
    except OSError:
        pass
    distro = distro.lower()
    if any(name in distro for name in ("debian", "ubuntu", "raspbian")):
        return "apt install network-manager"
    if any(name in distro for name in ("fedora", "rhel", "centos")):
        return "dnf install NetworkManager"
    if any(name in distro for name in ("arch",)):
        return "pacman -S networkmanager"
    return "install NetworkManager via your distro's package manager"


def main(argv: Optional[List[str]] = None) -> int:
    """Entry point for the ``racelink-setup-nmcli`` console script.

    Returns the desired process exit code so callers (or tests) can
    inspect outcomes without parsing stdout.
    """
    argv = list(argv) if argv is not None else list(sys.argv)

    if sys.platform != "linux":
        print(
            "error: racelink-setup-nmcli is Linux-only (NetworkManager / "
            f"polkit). Detected platform: {sys.platform}.",
            file=sys.stderr,
        )
        return 2

    if os.geteuid() != 0:
        print(
            "error: racelink-setup-nmcli must be run as root.\n"
            "Try:  sudo racelink-setup-nmcli",
            file=sys.stderr,
        )
        return 2

    install_hint = _check_nmcli()
    if install_hint is not None:
        print(
            "error: nmcli not found. Install NetworkManager first:\n"
            f"  {install_hint}",
            file=sys.stderr,
        )
        return 2

    try:
        user = _resolve_target_user(argv)
    except RuntimeError as ex:
        print(
            f"error: {ex}\n"
            "usage: sudo racelink-setup-nmcli [username]",
            file=sys.stderr,
        )
        return 2

    if not _user_exists(user):
        print(
            f"error: user {user!r} does not exist on this system.",
            file=sys.stderr,
        )
        return 2

    try:
        _install_groups(user)
        _write_polkit_rule(user)
        _reload_polkit()
    except (RuntimeError, OSError) as ex:
        print(f"error: {ex}", file=sys.stderr)
        return 1

    print()
    print(
        f"done. Verify by running (as {user}, after a fresh login):\n"
        "  nmcli dev wifi list\n"
        "If nmcli runs without asking for a password, the host is "
        "ready for OTA."
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
