#!/bin/bash
# Linux first-time setup helper for the RaceLink firmware-update flow.
#
# The host's OTA path uses ``nmcli dev wifi connect`` to associate to a
# WLED node's AP. Out of the box on most distros this requires either
# root or membership in the netdev (Debian/Ubuntu/Pi OS) or wheel
# (Fedora/RHEL) group, plus a polkit policy that authorises the running
# user. This script makes sure both are in place. Idempotent: re-run is
# a no-op once everything is configured.
#
# Usage (run once on the host that runs racelink-standalone):
#
#   sudo bash scripts/setup_nmcli_polkit.sh           # apply for $SUDO_USER
#   sudo bash scripts/setup_nmcli_polkit.sh alice     # apply for alice
#
# After it finishes, log out and back in (so group membership takes
# effect) and verify with:
#
#   nmcli dev wifi list
#
# If that lists nearby APs without prompting for a password, the host
# is ready to run firmware updates.

set -euo pipefail

USER_NAME="${1:-${SUDO_USER:-}}"
if [[ -z "${USER_NAME}" ]]; then
    echo "error: no username supplied (and \$SUDO_USER is empty)." >&2
    echo "usage: sudo bash $0 [username]" >&2
    exit 2
fi

if ! id "${USER_NAME}" >/dev/null 2>&1; then
    echo "error: user '${USER_NAME}' does not exist on this system." >&2
    exit 2
fi

if [[ "$(id -u)" -ne 0 ]]; then
    echo "error: must be run as root (use sudo)." >&2
    exit 2
fi

if ! command -v nmcli >/dev/null 2>&1; then
    echo "error: nmcli not found. Install NetworkManager first:"
    echo "  Debian/Ubuntu/Pi OS: apt install network-manager"
    echo "  Fedora:              dnf install NetworkManager"
    exit 2
fi

# 1) Group membership. ``netdev`` is the Debian/Ubuntu/Pi-OS convention;
# Fedora/RHEL use ``wheel`` for sudoers and don't have netdev. Add the
# user to whichever group exists; if neither exists we skip and rely on
# the polkit rule alone.
add_to_group() {
    local group="$1"
    if getent group "${group}" >/dev/null 2>&1; then
        if id -nG "${USER_NAME}" | tr ' ' '\n' | grep -qx "${group}"; then
            echo "user '${USER_NAME}' already in group '${group}'."
        else
            usermod -aG "${group}" "${USER_NAME}"
            echo "added '${USER_NAME}' to group '${group}'. Log out and back in for this to take effect."
        fi
        return 0
    fi
    return 1
}

if ! add_to_group "netdev"; then
    add_to_group "wheel" || echo "note: neither netdev nor wheel group present; relying on polkit rule below."
fi

# 2) Polkit rule. NetworkManager ships its own polkit defaults but
# different distros bind them to different groups. A short, explicit
# rule for the RaceLink user removes that ambiguity:
# any nm-related action, granted unconditionally to ${USER_NAME}.
# Stored under /etc/polkit-1/rules.d/ so it survives upgrades and
# overrides the upstream defaults that come from /usr/share/.
POLKIT_DIR="/etc/polkit-1/rules.d"
POLKIT_RULE="${POLKIT_DIR}/49-racelink-nmcli.rules"

mkdir -p "${POLKIT_DIR}"
cat >"${POLKIT_RULE}" <<EOF
// Auto-generated by RaceLink scripts/setup_nmcli_polkit.sh.
// Grants ${USER_NAME} unattended access to NetworkManager actions
// (wifi connect, radio toggle, profile up/down) used by the OTA
// flow. Re-run the setup script if you rename the user.
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.NetworkManager.") === 0 &&
        subject.user === "${USER_NAME}") {
        return polkit.Result.YES;
    }
});
EOF
chmod 644 "${POLKIT_RULE}"
echo "wrote ${POLKIT_RULE}"

# 3) Reload polkit so the rule activates without a reboot. systemctl is
# present everywhere we'd run this; if it's missing, a reboot would do
# the same job.
if command -v systemctl >/dev/null 2>&1; then
    systemctl reload polkit 2>/dev/null || systemctl restart polkit 2>/dev/null || true
fi

echo
echo "done. Verify by running (as ${USER_NAME}, after a fresh login):"
echo "  nmcli dev wifi list"
echo "If nmcli runs without asking for a password, the host is ready."
