from __future__ import annotations

from typing import Any, Callable, Protocol


class TransportPort(Protocol):
    def send_get_devices(self, recv3: bytes = b"\xFF\xFF\xFF", group_id: int = 0, flags: int = 0) -> None: ...

    def send_get_status(self, recv3: bytes = b"\xFF\xFF\xFF", group_id: int = 0, flags: int = 0) -> None: ...

    def send_set_group(self, recv3: bytes, group_id: int) -> None: ...

    def send_control(self, recv3: bytes, group_id: int, flags: int, preset_id: int, brightness: int) -> None: ...

    def send_config(
        self,
        recv3: bytes = b"\xFF\xFF\xFF",
        option: int = 0,
        data0: int = 0,
        data1: int = 0,
        data2: int = 0,
        data3: int = 0,
    ) -> None: ...

    def send_sync(self, recv3: bytes = b"\xFF\xFF\xFF", ts24: int = 0, brightness: int = 0) -> None: ...

    def send_stream(self, recv3: bytes, ctrl: int, data: bytes) -> None: ...

    def drain_events(self, timeout_s: float = 0.0): ...

    def add_listener(self, cb: Callable[[dict], None]) -> None: ...

    def remove_listener(self, cb: Callable[[dict], None]) -> None: ...

    def add_tx_listener(self, cb: Callable[[dict], None]) -> None: ...

    def close(self) -> None: ...


class ConfigStorePort(Protocol):
    def option(self, key: str, default: Any = None) -> Any: ...

    def option_set(self, key: str, value: Any) -> None: ...


class NotifierPort(Protocol):
    def notify(self, msg: str) -> None: ...


class DeviceLookupPort(Protocol):
    def get_device_by_address(self, addr: str): ...


class TransportCoordinatorPort(Protocol):
    def ensure_ready(self, context: str) -> bool: ...

    def install_hooks(self) -> None: ...

    def wait_rx_window(self, send_fn: Callable[[], None], collect_pred=None, fail_safe_s: float = 8.0): ...

    def send_and_wait_for_reply(self, recv3: bytes, opcode7: int, send_fn, timeout_s: float = 8.0): ...


from .host_ui import HostUIPort
from .host_race_events import HostRaceEventPort
