"""Auto-generated WLED effect/palette metadata. Do not edit by hand.

Generated by gen_wled_metadata.py from the WLED checkout at:
  C:/Users/psima/Dev/WLED LoRa/WLED
Regenerate when upgrading the bundled WLED firmware version.
"""

from __future__ import annotations

# Generated: 2026-04-29 13:59:50

# Source: wled00/data/index.js -- updateSelectedPalette()
# force_slot_min_palette[n] = lowest palette id that force-shows color slot n (inclusive).
# max_palette_id            = highest palette id the rule applies to (inclusive).
WLED_PALETTE_COLOR_RULES = {
    'force_slot_min_palette': [2, 3, 4],
    'max_palette_id': 5,
}
